FROM adoptopenjdk/openjdk11
ENV DATASOURCE_HOST=$DATASOURCE_HOST \
    DATASOURCE_PORT=$DATASOURCE_PORT \
    DATASOURCE_USERNAME=$DATASOURCE_USERNAME \
    DATASOURCE_PASSWORD=$DATASOURCE_PASSWORD \
    REDIS_HOST=$REDIS_HOST \
    REDIS_PORT=$REDIS_PORT \
    REDIS_PASSWORD=$REDIS_PASSWORD \
    SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE \
    OAUTH_KAKAO_CLIENT_ID=$OAUTH_KAKAO_CLIENT_ID \
    OAUTH_KAKAO_CLIENT_SECRET=$OAUTH_KAKAO_CLIENT_SECRET \
    OAUTH_KAKAO_REDIRECT_URL=$OAUTH_KAKAO_REDIRECT_URL \
    OAUTH_GOOGLE_CLIENT_ID=$OAUTH_GOOGLE_CLIENT_ID \
    OAUTH_GOOGLE_CLIENT_SECRET=$OAUTH_GOOGLE_CLIENT_SECRET \
    OAUTH_GOOGLE_REDIRECT_URL=$OAUTH_GOOGLE_REDIRECT_URL \
    S3_ACCESS_KEY=$S3_ACCESS_KEY \
    S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY \
    S3_BUCKET_NAME=$S3_BUCKET_NAME \
    S3_DIRECTORY_NAME=$S3_DIRECTORY_NAME \
    TZ=$TZ \
    CORS_ORIGIN_NAME=$CORS_ORIGIN_NAME

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]