FROM adoptopenjdk/openjdk11

ENV DATASOURCE_HOST=$DATASOURCE_HOST
ENV DATASOURCE_PORT=$DATASOURCE_PORT
ENV DATASOURCE_USERNAME=$DATASOURCE_USERNAME
ENV DATASOURCE_PASSWORD=$DATASOURCE_PASSWORD
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
ENV OAUTH_KAKAO_CLIENT_ID=$OAUTH_KAKAO_CLIENT_ID
ENV OAUTH_KAKAO_CLIENT_SECRET=$OAUTH_KAKAO_CLIENT_SECRET
ENV OAUTH_KAKAO_REDIRECT_URL=$OAUTH_KAKAO_REDIRECT_URL
ENV OAUTH_GOOGLE_CLIENT_ID=$OAUTH_GOOGLE_CLIENT_ID
ENV OAUTH_GOOGLE_CLIENT_SECRET=$OAUTH_GOOGLE_CLIENT_SECRET
ENV OAUTH_GOOGLE_REDIRECT_URL=$OAUTH_GOOGLE_REDIRECT_URL
ENV S3_ACCESS_KEY=$S3_ACCESS_KEY
ENV S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
ENV S3_BUCKET_NAME=$S3_BUCKET_NAME
ENV S3_DIRECTORY_NAME=$S3_DIRECTORY_NAME
ENV TZ=$TZ
ENV CORS_ORIGIN_NAME=$CORS_ORIGIN_NAME

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]