INSERT INTO RECORD_COLOR(RECORD_COLOR_ID, NAME, HEX_CODE, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'icon-purple', '#9067E5', now(), now(), null);
INSERT INTO RECORD_COLOR(RECORD_COLOR_ID, NAME, HEX_CODE, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'icon-yellow', '#F3D06C', now(), now(), null);
INSERT INTO RECORD_COLOR(RECORD_COLOR_ID, NAME, HEX_CODE, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'icon-pink', '#D78A86', now(), now(), null);
INSERT INTO RECORD_COLOR(RECORD_COLOR_ID, NAME, HEX_CODE, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'icon-blue', '#6F99F2', now(), now(), null);
INSERT INTO RECORD_COLOR(RECORD_COLOR_ID, NAME, HEX_CODE, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'icon-green', '#78BCB7', now(), now(), null);