INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'crown', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'gift', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'heart', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'like', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'lock', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'modal', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'moon', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'music', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'rocket', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'speechbubble', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'trashcan', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'umbrella', now(), now(), null);
INSERT INTO RECORD_ICON(RECORD_ICON_ID, NAME, CREATED_AT, MODIFIED_AT, DELETED_AT)
VALUES (null, 'wine', now(), now(), null);